@echo off
chcp 65001
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить SmartSceen и блокировку загрузок.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить исполняемый файл службы защиты от вредоносных программ.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить менеджер загрузки карт.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить службы диагностики и телеметрии.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Принудительно закрыть все процессы и службы(Безопасно).bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Остановить всю работу в фоне для Windows 11.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключение Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить антивирус Windows.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить карты.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить обновления Windows.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить триггеры.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Удалить телеметрию Nvidia.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить Cortana.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить Xbox.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить другое.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить историю.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить планы.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить сбор.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить службы.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключение Cortana.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить Defender, SmartScreen и Antimalware.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить все типы синхронизыции.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить сбор данных об установленных приложениях.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить эксперименты над ПК.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить Cortana.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить «Новости и интересы».bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить безопасный режим Защитника Windows.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить общий доступ к медиаплееру.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить общий доступ к файлам.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить пограничную телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить протокол SMBv1.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить протокол SMBv2.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить рекламу в Проводнике.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию Office.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию Visual Studio.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию Xbox.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить Cortana.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить автоматическое обновление Windows.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить и Xbox сервисы.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить историю для приложений.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить потенциально уязвимые службы.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить сохранение списков последних открытых файлов.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Очистка файла подкачки.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Убрать из планировщика запланированные задачи телеметрии.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение «журналирования» Событий Windows.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение ведения записи поведения пользователя.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение всех видов телеметрий Office.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение всех видов телеметрий Windows.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение всех типов синхронизаций Windows.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение и выпиливание шпионских модулей Microsoft.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение определения местоположения пользователя.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение проверки обращений через «Обратную связь».bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение рекламного идентификатора и рекламы.bat"
cmd /c "tweaks\Оптимизация\Оптимизация MartyFiles\Ускорить запуск Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Остановить всю работу в фоне для Windows 11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключение Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить антивирус Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Удалить телеметрию Nvidia.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Качество фона 100.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить BitLocker.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить Ease Of Access.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить Защитник Windows.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Google Chrome\Delete Chrome Bloatware.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Google Chrome\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Microsoft Edge\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Mozilla Firefox\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Yandex Browser\Delete Telemetry.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Отключить гибернацию.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистить Windows v2.0.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистить временные файлы и кэш иконок.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка кэша обновлений.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка от Igromanoff.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка папок Temp.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка файла подкачки.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка хранилища WinSxS.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Удалить временные файлы.bat"
cmd /c "tweaks\Главная\Анонимность\Все твики O&O ShutUp10++.bat"
cmd /c "tweaks\Главная\Анонимность\Максимальная конфиденциальность от DE3NAKE.bat"
cmd /c "tweaks\Главная\Анонимность\Отключить новую телеметрию Windows за 2024 год.bat"
cmd /c "tweaks\Главная\Анонимность\Приватность и отпимизация от ReviOS.bat"
cmd /c "tweaks\Главная\Анонимность\Приватность от WPD.bat"
cmd /c "tweaks\Главная\Анонимность\Рекомендуемые и условныетвики O&O ShutUp10++.bat"
cmd /c "tweaks\Главная\Анонимность\Рекомендуемые твики O&O ShutUp10++.bat"
cmd /c "tweaks\Главная\Анонимность\Терапия после обновлений винды.bat"
cmd /c "tweaks\Главная\Бэкап\Реестр\Сделать бекап реестра от DE3NAKE.cmd"
cmd /c "tweaks\Главная\Бэкап\Реестр\Сделать копию реестра от разработчика.bat"
cmd /c "tweaks\Главная\Другое\Отключить UAC и smartscreen.bat"
cmd /c "tweaks\Главная\Обновления\Запретить Windows 10 восстановить себя от Windows Update.bat"
cmd /c "tweaks\Главная\Обновления\Отключить автоматическое обновление Windows.bat"
cmd /c "tweaks\Главная\Обновления\Отключить обновления Windows 10.bat"
cmd /c "tweaks\Главная\Обновления\Отключить обновления Windows от ios1ph.bat"
cmd /c "tweaks\Главная\Обновления\Отключить службу Windows Update.bat"
cmd /c "tweaks\Главная\Обновления\Удалить скачанные файлы обновлений Windows.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Выключить автообновление драйверов.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить UAC и smartscreen.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить обновления Windows.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить оптимизацию доставки.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить триггеры.bat"
cmd /c "tweaks\Оптимизация\Оптимизация MartyFiles\Ускорить запуск Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Остановить всю работу в фоне для Windows 11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключение Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить антивирус Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Удалить телеметрию Nvidia.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Качество фона 100.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить BitLocker.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить Ease Of Access.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить Защитник Windows.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Google Chrome\Delete Chrome Bloatware.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Google Chrome\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Microsoft Edge\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Mozilla Firefox\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Yandex Browser\Delete Telemetry.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистить Windows v2.0.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистить временные файлы и кэш иконок.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка кэша обновлений.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка от Igromanoff.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка папок Temp.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка файла подкачки.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка хранилища WinSxS.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Удалить временные файлы.bat"