@echo off
chcp 65001
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить SmartSceen и блокировку загрузок.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить исполняемый файл службы защиты от вредоносных программ.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить менеджер загрузки карт.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить службы диагностики и телеметрии.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Принудительно закрыть все процессы и службы(Безопасно).bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Остановить всю работу в фоне для Windows 11.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключение Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить антивирус Windows.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить карты.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить обновления Windows.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить триггеры.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Удалить телеметрию Nvidia.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить Cortana.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить Xbox.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить другое.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить историю.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить планы.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить сбор.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить службы.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключение Cortana.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить Defender, SmartScreen и Antimalware.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить все типы синхронизыции.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить сбор данных об установленных приложениях.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить эксперименты над ПК.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить Cortana.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить «Новости и интересы».bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить безопасный режим Защитника Windows.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить общий доступ к медиаплееру.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить общий доступ к файлам.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить пограничную телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить протокол SMBv1.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить протокол SMBv2.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить рекламу в Проводнике.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию Office.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию Visual Studio.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию Xbox.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить Cortana.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить автоматическое обновление Windows.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить и Xbox сервисы.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить историю для приложений.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить потенциально уязвимые службы.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить сохранение списков последних открытых файлов.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Очистка файла подкачки.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Убрать из планировщика запланированные задачи телеметрии.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение «журналирования» Событий Windows.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение ведения записи поведения пользователя.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение всех видов телеметрий Office.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение всех видов телеметрий Windows.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение всех типов синхронизаций Windows.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение и выпиливание шпионских модулей Microsoft.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение определения местоположения пользователя.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение проверки обращений через «Обратную связь».bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение рекламного идентификатора и рекламы.bat"
cmd /c "tweaks\Оптимизация\Оптимизация MartyFiles\Ускорить запуск Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Остановить всю работу в фоне для Windows 11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключение Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить антивирус Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Удалить телеметрию Nvidia.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Качество фона 100.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить BitLocker.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить Ease Of Access.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить Защитник Windows.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Google Chrome\Delete Chrome Bloatware.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Google Chrome\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Microsoft Edge\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Mozilla Firefox\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Yandex Browser\Delete Telemetry.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Отключить гибернацию.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистить Windows v2.0.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистить временные файлы и кэш иконок.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка кэша обновлений.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка от Igromanoff.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка папок Temp.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка файла подкачки.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка хранилища WinSxS.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Удалить временные файлы.bat"
cmd /c "tweaks\Главная\Анонимность\Все твики O&O ShutUp10++.bat"
cmd /c "tweaks\Главная\Анонимность\Максимальная конфиденциальность от DE3NAKE.bat"
cmd /c "tweaks\Главная\Анонимность\Отключить новую телеметрию Windows за 2024 год.bat"
cmd /c "tweaks\Главная\Анонимность\Приватность и отпимизация от ReviOS.bat"
cmd /c "tweaks\Главная\Анонимность\Приватность от WPD.bat"
cmd /c "tweaks\Главная\Анонимность\Рекомендуемые и условныетвики O&O ShutUp10++.bat"
cmd /c "tweaks\Главная\Анонимность\Рекомендуемые твики O&O ShutUp10++.bat"
cmd /c "tweaks\Главная\Анонимность\Терапия после обновлений винды.bat"
cmd /c "tweaks\Главная\Бэкап\Реестр\Сделать бекап реестра от DE3NAKE.cmd"
cmd /c "tweaks\Главная\Бэкап\Реестр\Сделать копию реестра от разработчика.bat"
cmd /c "tweaks\Главная\Другое\Отключить UAC и smartscreen.bat"
cmd /c "tweaks\Главная\Обновления\Запретить Windows 10 восстановить себя от Windows Update.bat"
cmd /c "tweaks\Главная\Обновления\Отключить автоматическое обновление Windows.bat"
cmd /c "tweaks\Главная\Обновления\Отключить обновления Windows 10.bat"
cmd /c "tweaks\Главная\Обновления\Отключить обновления Windows от ios1ph.bat"
cmd /c "tweaks\Главная\Обновления\Отключить службу Windows Update.bat"
cmd /c "tweaks\Главная\Обновления\Удалить скачанные файлы обновлений Windows.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Выключить автообновление драйверов.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить UAC и smartscreen.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить обновления Windows.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить оптимизацию доставки.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Главная\Обновления\Терапия после обновления Windows\Отключить триггеры.bat"
cmd /c "tweaks\Оптимизация\Оптимизация MartyFiles\Ускорить запуск Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Остановить всю работу в фоне для Windows 11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключение Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить антивирус Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Удалить телеметрию Nvidia.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Качество фона 100.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить BitLocker.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить Ease Of Access.bat"
cmd /c "tweaks\Оптимизация\Остальное\Отключить Защитник Windows.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Google Chrome\Delete Chrome Bloatware.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Google Chrome\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Microsoft Edge\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Mozilla Firefox\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Yandex Browser\Delete Telemetry.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистить Windows v2.0.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистить временные файлы и кэш иконок.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка кэша обновлений.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка от Igromanoff.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка папок Temp.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка файла подкачки.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Очистка хранилища WinSxS.bat"
cmd /c "tweaks\Очистка\Классическая очистка\Удалить временные файлы.bat"
cmd /c "tweaks\Главная\Другое\Отключить UAC и smartscreen.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключите дополнительные ненужные службы.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить SmartSceen и блокировку загрузок.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить взаимодействие с подключенными пользователями и телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить Защитник (включая исполняемый файл службы защиты от вредоносных программ).bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить исполняемый файл службы защиты от вредоносных программ.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить менеджер загрузки карт.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить службы Bluetooth.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить службы Xbox.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить службы диагностики и телеметрии.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Отключить службы принтера.bat"
cmd /c "tweaks\Главная\Приватность\Adamx\Принудительно закрыть все процессы и службы(Безопасно).bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Выключить автообновление драйверов.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Остановить всю работу в фоне для Windows 10.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Остановить всю работу в фоне для Windows 11.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключение Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить антивирус Windows.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить виджеты для Windows 11.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить карты.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить обновления Windows.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Отключить триггеры.bat"
cmd /c "tweaks\Главная\Приватность\BoosterX и ios1ph\Удалить телеметрию Nvidia.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить Cortana.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить Xbox.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить другое.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить историю.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить планы.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить сбор.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить службы.bat"
cmd /c "tweaks\Главная\Приватность\IT-спец. Денис Курец\Отключить телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключение Cortana.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить Defender, SmartScreen и Antimalware.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить все типы синхронизыции.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить сбор данных об установленных приложениях.bat"
cmd /c "tweaks\Главная\Приватность\MartyFiles\Отключить эксперименты над ПК.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить Cortana.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить «Новости и интересы».bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить безопасный режим Защитника Windows.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить общий доступ к медиаплееру.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить общий доступ к файлам.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить пограничную телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить протокол SMBv1.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить протокол SMBv2.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить рекламу в Проводнике.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию Office.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию Visual Studio.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию Xbox.bat"
cmd /c "tweaks\Главная\Приватность\Optimizer\Отключить телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить Cortana.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить автоматическое обновление Windows.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить ведение истории поисковых запросов.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить и Xbox сервисы.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить историю для приложений.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить потенциально уязвимые службы.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить сохранение списков последних открытых файлов.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Отключить телеметрию.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Очистка файла подкачки.bat"
cmd /c "tweaks\Главная\Приватность\Pulse\Убрать из планировщика запланированные задачи телеметрии.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение «журналирования» Событий Windows.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение ведения записи поведения пользователя.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение всех видов телеметрий Office.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение всех видов телеметрий Windows.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение всех типов синхронизаций Windows.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение и выпиливание шпионских модулей Microsoft.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение определения местоположения пользователя.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение проверки обращений через «Обратную связь».bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение рекламного идентификатора и рекламы.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение сбора данных об установленных приложениях.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение сбора данных через события планировщика.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение сбора и отправки данных рукописного ввода.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение сбора статистики использования приложений.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение сетевого доступа к доменам сбора данных.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение скрытого мониторинга системы.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение скрытого фонового обновления синтеза речи.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение телеметрии NVIDIA.bat"
cmd /c "tweaks\Главная\Приватность\Win 10 Tweaker\Отключение удалённых экспериментов над ПК.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Блокировать нежелательные веб узлы в файл hosts.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Блокировка портов (безопасность).bat"
cmd /c "tweaks\Главная\Приватность\windowser\Добавление правил брандмауэра. Блокировка нежелательных IP адресов.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить биометрическую службу Windows.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить все службы Xbox.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить камеру.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить нежелательные свойства Windows.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить обслуживание сенсорной клавиатуры и панели рукописного ввода.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить поиск в Windows.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить протокол SMB (общий доступ к файлам и принтерам).bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить розничную демонстрационную услугу.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить службу Bluetooth.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить службу Windows Update.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить службу геолокации.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить службу менеджера скачанных карт.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить службу общего доступа к проигрывателю Windows Media по сети.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить службу помощника по совместимости программ.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить службу предварительной оценки Windows.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить службу родительского контроля.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить службу удаленного реестора.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить службу управления корпоративными приложениями.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Отключить Центр безопасности.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Приватность Windows 10.bat"
cmd /c "tweaks\Главная\Приватность\windowser\Удалить шпионские службы от windowser.bat"
cmd /c "tweaks\Главная\Приватность\Отключить телеметрию Браузеров\Оптимизировать и удалить телеметрию Google Chrome.bat"
cmd /c "tweaks\Главная\Приватность\Отключить телеметрию Браузеров\Отключить телеметрию Microsoft Edge.bat"
cmd /c "tweaks\Главная\Приватность\Отключить телеметрию Браузеров\Отключить телеметрию Mozilla Firefox.bat"
cmd /c "tweaks\Главная\Приватность\Отключить телеметрию Браузеров\Отключить телеметрию Яндекс Браузера.bat"
cmd /c "tweaks\Оптимизация\Оптимизация MartyFiles\Ускорение частоты мерцания курсора.bat"
cmd /c "tweaks\Оптимизация\Оптимизация MartyFiles\Ускорить запуск Windows.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Rebuild Performance Counters (Run As Admin).cmd"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Удалить мусор гугл хрома.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\DirectX default - вернуть все как было.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Включить аппаратное ускорение.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Включить вспомогательные драйвера программной прорисовки графики.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Включить расширенные функции Direct3D.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Настройка AGP Texturing.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Оптимизировать MMX.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Отключить Few Vertices.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Отключить VSync.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Отключить отладку.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Отключить принудительное использование NoSysLock.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Отключить режим совместимости (ModeX) для старых EGA-видеокарт.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Реагировать на нажатие клавиши PrintScreen.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация DirectX\Увеличение быстродействия VRAM.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация и чистка диска\Вырубить обслуживание HDD SSD.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Оптимизация и чистка диска\Вернуть\Включить обслуживание HDD SSD.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Отключение служб\Второй способ\Disable Windows Updates.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Отключение служб\Первый способ\Рекомендованные службы 2.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Отключение телеметрии\disable telemetry faceit.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Отключение телеметрии\disable telemetry fix net.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Отключение телеметрии\disable telemetry.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Твики для оптимизации\Windows Priority game tweak.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Твики для оптимизации\Приоритизация игры (инпут).bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Твики для оптимизации\УБрать смарт скрин.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Твики для оптимизации\Фулл скрин фикс.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Твики для уменьшение задержки\Input Delay.bat"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Электропитание\Amit_v1_lowlatency.pow"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Электропитание\Amit_v2_extreme performance.pow"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Электропитание\Amit_v3_low latency.pow"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Электропитание\Atlas Power Plan.pow"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Электропитание\Bitsum Highest Performance.pow"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Электропитание\Calypto.pow"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Электропитание\GGOSv0_8_5_Idle_Enabled.pow"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Электропитание\Muren_Idle_Enabled.pow"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Электропитание\Unixcorn_Idle_Enabled.pow"
cmd /c "tweaks\Оптимизация\Безопасная оптимизация\Электропитание\Zoyata_Low Latency.pow"
cmd /c "tweaks\Оптимизация\Основная оптимизация\W10 Старое меню питании.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Включить GameMode.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключение залипания клавиш.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключить FSO и GameBar.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключить автостарт программ.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключить прозрачность.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключить уведомления защиты.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Остановить всю работу в фоне для Windows 11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключение Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить антивирус Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить брандмауер.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить виджеты для Windows 11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить карты.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить оптимизацию доставки.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Открыть параметры быстродействия.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Старое контекстное меню для Windows 11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Удалить телеметрию Nvidia.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Brave\Delete Brave Bloatware.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Google Chrome\Delete Chrome Bloatware.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Google Chrome\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Microsoft Edge\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Mozilla Firefox\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Mozilla Firefox\Firefox Debloat.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Браузеры\Yandex Browser\Delete Telemetry.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\CS2\CS2_Low_Latency.ps1"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\CS2\net.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Fortnite\1 HIT REGISTRY\HIT REG.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Fortnite\1 HIT REGISTRY\network.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Fortnite\2 Настройка\autorun.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Fortnite\2 Настройка\unautorun.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Fortnite\2 Настройка\Clean\cleanrubishauto.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Fortnite\2 Настройка\Clean\unrun.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Fortnite\2 Настройка\Effects\unrun.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Fortnite\2 Настройка\Maps\unrun.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Fortnite\4 fortnite potato graphics\мыльные скины.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Standoff\Звуки SpeedyTerror(для стандофа)\1.exe"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Standoff\Звуки SpeedyTerror(для стандофа)\3.exe"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Standoff\Звуки SpeedyTerror(для стандофа)\PcEqualizer.exe"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Игры\Valorant\Use if you play Valorant after tweaks.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Приложения\Discord\Anton_Vampir.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Приложения\Discord\Discord Debloat.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Приложения\Discord\main.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Приложения\Razer\razer.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Приложения\Spotify\Cut Spotify.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Приложения\Spotify\HYPERTWEAKS SpotifyRemoveLanguages.bat"
cmd /c "tweaks\Оптимизация\Оптимизация программ\Приложения\Windows app\Debloat all Windows Apps.bat"
cmd /c "tweaks\Электропитание\Твики\Режим ожидания.bat"
cmd /c "tweaks\Электропитание\Твики\Хранилище D3 в современном режиме ожидания.bat"
cmd /c "tweaks\Другое\Программы\Оптимизация\Mem Reduct.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Desktop tweaks.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Keyboard Data Queue 50.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Large System Cache.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Mouse Data Queue 54 (ios1ph recommended).bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\NetworkThrottling.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\System Responsiveness.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Более жесткая уборка.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Выключить службы брандмауера.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Вырубить обслуживание HDD SSD.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Качество фона 100.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Отключить автообновления store.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Отключить обновления Windows.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Открывать pow файлы.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Рекомендованные службы 2.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Рекомендованные службы.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Тесты режимов электропитания.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Ускорить завершение работы.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Установить оптимизацию при входе.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\startup\startup.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Лагает Windows после углубленки\2) Удалить оптимизацию.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Лагает Windows после углубленки\3) Установить оптимизацию.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Лагает Windows после углубленки\5) Убрать поток с процессов.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Лагает Windows после углубленки\startup\startup.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Amit_v1_lowlatency.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Amit_v2_extreme performance.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Amit_v3_low latency.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Atlas Power Plan.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Bitsum Highest Performance.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Calypto.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\GGOSv0_8_5_Idle_Enabled.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Muren_Idle_Enabled.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Unixcorn_Idle_Enabled.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Zoyata_Low Latency.pow"
